agent_name: impact_evaluator
author: valory
version: 0.1.0
license: Apache-2.0
description: The impact evaluator agent.
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeialhcja5fhf2ahyx5no2aajvnfhh4tj7ihhx65qpoohc4n5wfr76q
  tests/__init__.py: bafybeibknjewfed3d5ypi46ipuzfxdcps5ief2hfd3a2tfvm4gjtzzblme
  tests/helpers/__init__.py: bafybeif7verbag26h6i35gr5rlatxl7veq4drup5ykwdvhgtussf2jreei
  tests/helpers/constants.py: bafybeibbokz7gzdlubnjwxrmh4tqckc7j75hfy3ae6l5a63mrbd4hp6l7u
  tests/helpers/data/json_server/data.json: bafybeid3uvl3vnmudpanc64wgwdvxwlyajnuolivrqpdypa5ortdb66a6a
  tests/helpers/docker.py: bafybeihlg5thdrcaiuzyte5s7x25mikqfyxdjwuqvhmeddluyjdkzhuhqi
  tests/helpers/fixtures.py: bafybeidfsamzdrqqkdra4ektollyfkhiyb2iqymy6djavgewon2cb23vwu
  tests/test_impact_evaluator.py: bafybeigu6nx4j4ll7neegopt5h55ijvbaj7depnyjpo5e2z6bsnfci6hs4
fingerprint_ignore_patterns: []
connections:
- valory/http_server:0.22.0:bafybeihpgu56ovmq4npazdbh6y6ru5i7zuv6wvdglpxavsckyih56smu7m
- valory/abci:0.1.0:bafybeifr35jcajq2lqnj2rd5lueo4g5nysbvbaacdchfecwgtcojqx3mie
- valory/http_client:0.23.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- valory/ledger:0.19.0:bafybeig7woeog4srdby75hpjkmx4rhpkzncbf4h2pm5r6varsp26pf2uhu
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
- valory/openai:0.1.0:bafybeigyehjbahya5mp7vyp5tjvn36rey4btvzskp3ql3mgxp3zu6gwq5a
- valory/twitter:0.1.0:bafybeidcalgczvpoq6l2uh7kkfblwxmytm6bicmsxub7pevu2k46sp7mky
contracts:
- valory/dynamic_contribution:0.1.0:bafybeia4qhu3u3fl6gx5vk7ue3qadbcliltuvcx46zsxcffq7phsb54rbq
- valory/gnosis_safe:0.1.0:bafybeibbglwlfvytwcphk6pccdbzubpfh2hmmi2me35bxzic32cepectje
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeibkdn73yvpkuwm3holsunklhzdnuwunhebrwnxkxq25liq36ect4m
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- valory/service_registry:0.1.0:bafybeih4ao44fkkrdofzcf6d2oem6tx4pjo6g27ang5junmcwtw3w4tyra
- valory/veolas_delegation:0.1.0:bafybeieicrbkito2hglwvd4j2cbq3etxpm3rrzfyx5kqqe34fu7q5aftye
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/llm:1.0.0:bafybeihj2orqapokafg7co3wlogwgf6cckaaj2bz3nuv4rm3opkoyhrlp4
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
- valory/twitter:0.1.0:bafybeig7dugazhljpb4qtu4zfnoimttvivopiq574rogjz3qggf5eysnk4
skills:
- valory/abstract_abci:0.1.0:bafybeibzxex6md6xp5eibvp23cmkk7xgdyd44r5lxhfhlquwe3nb22ujgy
- valory/abstract_round_abci:0.1.0:bafybeih2soag6gy472x7vbbxmetmr532jqzm2efcapymi3725as33fvjvu
- valory/impact_evaluator_abci:0.1.0:bafybeih635uqxsx4ijyhn6sq5pr72qfyzqcd7naknwx3s4lft65wfd524i
- valory/generic_scoring_abci:0.1.0:bafybeihpynv3565stc7fsahgesmeetklqzqbvj3f2ipxlnh3bzna3hypcy
- valory/twitter_scoring_abci:0.1.0:bafybeif42fwffcttuuwnegrupczchy55vzce53xiuhxyqjdxmmysmn23ru
- valory/ceramic_read_abci:0.1.0:bafybeih3ihqbd4x5wy7jpkg4mvrp2rlgm3pkcgzukkfu7clcivd444vcvq
- valory/ceramic_write_abci:0.1.0:bafybeia66sapsttlkalawanhgztk4hnv673x32w3vgz6si24nazowqcube
- valory/dynamic_nft_abci:0.1.0:bafybeig7nfr5cmqevs2sbdubm5x4chrsszuxqy2s7jxllaqcb3dt2qw4ey
- valory/registration_abci:0.1.0:bafybeiaxomjnv2h7ozc7mvmz5wysfinfgtqnniznpcdunijb5iiekv4mzi
- valory/reset_pause_abci:0.1.0:bafybeiatyhxriq2gzny3s5by2plk7tyw4o5uvabzuhvhvwrl2pburbdjcm
- valory/termination_abci:0.1.0:bafybeig3gpsgm4c2ibywmriv2py6224xxsfw5b6p6j3gc7szz3qv22bhce
- valory/transaction_settlement_abci:0.1.0:bafybeicq4ttsarwurbll4xqabjb26g3po2ntrcxkwi7vac6d2kmvt6hati
- valory/twitter_write_abci:0.1.0:bafybeiaofknda4gzs6xks53ta5xwhgs2dvyvfqypdk2ey7if6egjpgarna
- valory/decision_making_abci:0.1.0:bafybeid2ek6ffalgebg2kjvwbaxppswiqarx423ctn7q2fwwvzi75n3de4
- valory/llm_abci:0.1.0:bafybeicljcawuikys472glztza4mfj7ccl2eqxcbptysl7tdexik6w6zvm
- valory/olas_week_abci:0.1.0:bafybeiafopl7jgspashjnrsxikcimn7yjyuihe32hlcohbppwbtot4j3my
- valory/mech_interact_abci:0.1.0:bafybeicj4c6brjtijdqywn3knejwl4o5ynzi4jcc4sinezeyj7lbgxbu5q
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.53.0
default_connection: null
---
public_id: valory/openai:0.1.0
type: connection
config:
  engine: ${str:text-davinci-003}
  max_tokens: ${int:500}
  openai_api_key: ${str:null}
  temperature: ${float:0.7}
  use_staging_api: ${bool:false}
  staging_api: ${str:http://host.docker.internal:5000/openai}
---
public_id: valory/twitter:0.1.0
type: connection
config:
  access_secret: ${str:<access_secret>}
  access_token: ${str:<access_token>}
  auth_token: ${str:<auth_token>}
  consumer_key: ${str:<consumer_key>}
  consumer_secret: ${str:<consumer_secret>}
  use_staging_api: ${bool:false}
  staging_api: ${str:http://host.docker.internal:5000/twitter/create_tweet}
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/impact_evaluator_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
    gnosis:
      address: ${str:http://localhost:8545}
      chain_id: ${int:1337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: valory/impact_evaluator_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/logs}
  params:
    args:
      centaurs_stream_id: ${str:kjzl6cwe1jw146h5momfk1vwzjq9vtg2ic4c1h5893usybetw3x338gu0ui2iih}
      manual_points_stream_id: ${str:manual_points_stream_id}
      ceramic_db_stream_id: ${str:ceramic_db_stream_id}
      ceramic_api_base: ${str:https://ceramic-clay.3boxlabs.com/}
      ceramic_api_create_endpoint: ${str:api/v0/streams}
      ceramic_api_commit_endpoint: ${str:api/v0/commits}
      ceramic_api_read_endpoint: ${str:api/v0/commits/{stream_id}}
      ceramic_did_seed: ${str:0101010101010101010101010101010101010101010101010101010101010101}
      ceramic_did_str: ${str:z6Mkon3Necd6NkkyfoGoHxid2znGc59LU3K7mubaRcFbLfLX}
      default_read_target_property: ${str:default_read_target_property}
      default_write_target_property: ${str:default_write_target_property}
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      dynamic_contribution_contract_address: ${str:0x5FbDB2315678afecb367f032d93F642f64180aa3}
      earliest_block_to_monitor: ${int:8053690}
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0x0000000000000000000000000000000000000000}
      termination_sleep: ${int:900}
      init_fallback_gas: 0
      keeper_allowed_retries: 3
      reset_pause_duration: ${int:300}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: ${int:2}
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      tweet_evaluation_round_timeout: ${float:600.0}
      service_id: impact_evaluator
      service_registry_address: ${str:null}
      setup:
        all_participants: ${list:["0x10E867Ac2Fb0Aa156ca81eF440a5cdf373bE1AaC"]}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      token_uri_base: ${str:https://pfp.staging.autonolas.tech/}
      whitelist_api_key: null
      whitelist_endpoint: http://localhost
      points_to_image_hashes: ${str:{}}
      twitter_api_base: ${str:https://api.twitter.com/}
      twitter_api_bearer_token: ${str:<default_bearer_token>}
      twitter_mentions_endpoint: ${str:2/users/1450081635559428107/mentions?}
      twitter_mentions_args: ${str:tweet.fields=author_id&user.fields=name&expansions=author_id&max_results={max_results}&since_id={since_id}}
      twitter_max_pages: ${int:1}
      max_tweet_pulls_allowed: ${int:80}
      twitter_search_endpoint: ${str:2/tweets/search/recent?}
      twitter_search_args: ${str:query=%23olas&tweet.fields=author_id,created_at,conversation_id&user.fields=name&expansions=author_id&max_results={max_results}&since_id={since_id}}
      twitter_tweets_endpoint: ${str:2/users/1450081635559428107/tweets?}
      twitter_tweets_args: ${str:tweet.fields=author_id,created_at,conversation_id&user.fields=name&expansions=author_id&max_results=50&start_time={start_time}}
      openai_call_window_size: ${float:3600.0}
      openai_calls_allowed_in_window: ${int:100}
      tx_timeout: 10.0
      use_termination: ${bool:false}
      validate_timeout: 1205
      finalize_timeout: 60.0
      history_check_timeout: 1205
      centaur_id_to_secrets: ${str:{}}
      max_points_per_period: ${int:5000}
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      multisend_batch_size: ${int:50}
      mech_contract_address: ${str:0x77af31De935740567Cf4fF1986D04B2c964A786a}
      mech_request_price: ${int:null}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      default_chain_id: ${str:ethereum}
      transaction_service_url: ${str:https://safe-transaction-mainnet.safe.global/api/v1/messages/{message_hash}/}
      veolas_delegation_address: ${str:0x2f1ea3bc39f1a052460cac722e64c1f89c3c1e68}
      tweet_consensus_veolas: ${int:2000000}
      termination_from_block: ${int:0}
      mech_chain_id: ${str:gnosis}
      mech_interaction_sleep_time: ${int:10}
  randomness_api:
    args:
      api_id: cloudflare
      headers: {}
      method: GET
      parameters: {}
      response_key: null
      response_type: dict
      retries: 5
      url: ${str:https://drand.cloudflare.com/public/latest}
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/impact_evaluator_abci:0.1.0
