agent_name: impact_evaluator
author: valory
version: 0.1.0
license: Apache-2.0
description: The impact evaluator agent.
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeialhcja5fhf2ahyx5no2aajvnfhh4tj7ihhx65qpoohc4n5wfr76q
  tests/__init__.py: bafybeibknjewfed3d5ypi46ipuzfxdcps5ief2hfd3a2tfvm4gjtzzblme
  tests/helpers/__init__.py: bafybeif7verbag26h6i35gr5rlatxl7veq4drup5ykwdvhgtussf2jreei
  tests/helpers/constants.py: bafybeibbokz7gzdlubnjwxrmh4tqckc7j75hfy3ae6l5a63mrbd4hp6l7u
  tests/helpers/data/json_server/data.json: bafybeidjhs6bp4vvkbuetddg4yq6ilvqobq755cixq2vv233k2u352rq7m
  tests/helpers/docker.py: bafybeihlg5thdrcaiuzyte5s7x25mikqfyxdjwuqvhmeddluyjdkzhuhqi
  tests/helpers/fixtures.py: bafybeidfsamzdrqqkdra4ektollyfkhiyb2iqymy6djavgewon2cb23vwu
  tests/test_impact_evaluator.py: bafybeiazdcvzsmm2h6h5ufx4bjdwcwbzlexemot3kjp6h6gayrrpwt4kpm
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.22.0:bafybeihaax5od5zo5jk2l62hv4jwuwtxloh5mijozudpsjombqc4ncmi6i
- valory/abci:0.1.0:bafybeie7fsmdzatyofhagfice7afbmyn7ht3zuzojdlu6cjaz7zncjspfq
- valory/http_client:0.23.0:bafybeidykl4elwbcjkqn32wt5h4h7tlpeqovrcq3c5bcplt6nhpznhgczi
- valory/ledger:0.19.0:bafybeicgfupeudtmvehbwziqfxiz6ztsxr5rxzvalzvsdsspzz73o5fzfi
- valory/p2p_libp2p_client:0.1.0:bafybeidwcobzb7ut3efegoedad7jfckvt2n6prcmd4g7xnkm6hp6aafrva
contracts:
- valory/dynamic_contribution:0.1.0:bafybeihsbxrubmhusp7jes237ft2pped44xthoewfckzciivj7ecjr6jga
protocols:
- open_aea/signing:1.0.0:bafybeibqlfmikg5hk4phzak6gqzhpkt6akckx7xppbp53mvwt6r73h7tk4
- valory/contract_api:1.0.0:bafybeidv6wxpjyb2sdyibnmmum45et4zcla6tl63bnol6ztyoqvpl4spmy
- valory/http:1.0.0:bafybeifyoio7nlh5zzyn5yz7krkou56l22to3cwg7gw5v5o3vxwklibhty
skills:
- valory/abstract_abci:0.1.0:bafybeifeqstiynx2n37k7lpdbcclylgg7tsmym7vtj4tanrukkvw4pp5nu
- valory/abstract_round_abci:0.1.0:bafybeiarzpxsy7ulitk5obs4zajhll2m77motjn5st7mi6qvjtkoirfikq
- valory/impact_evaluator_abci:0.1.0:bafybeift24ugfkhjo7p2u6yswwd7qlnkoeaatdjr5yxgfcec35xhzitph4
- valory/path_switch_abci:0.1.0:bafybeidv2khcgwjhm3w35vr6cl3tx2up4ljrl6pyjpuie4pdqbo2jmgoqm
- valory/generic_scoring_abci:0.1.0:bafybeiawjbzn23pxihgdnwyccxqyuh7yyvvhd3s745amlvgxpg3qqfzh4e
- valory/twitter_scoring_abci:0.1.0:bafybeih2qknxr3x6cwwrn64ol6r26gw3q7qhraqjmkvux6mwhkaseem45a
- valory/ceramic_read_abci:0.1.0:bafybeif2vkjwspf2yznau7z2thrhiwwynz2fdg3zxcbv5r3ltqrjmpwc5a
- valory/ceramic_write_abci:0.1.0:bafybeiflbg6xwjylqflkd4lyh5ajkmvrgkxa36gprcbcrm7ob6gnytshle
- valory/dynamic_nft_abci:0.1.0:bafybeifw62se34a4x4rciulzds3m4voahhyg4wfxcn7afwpkxsgzmxqmji
- valory/registration_abci:0.1.0:bafybeie4suynydmpq2myqkdzhiqoro2hr4zexd5a2o4rvch7yefw65kjvq
- valory/reset_pause_abci:0.1.0:bafybeiaickab63rqbu3kywnwyrfaa4362ai7rbvhghehxnvqk54eiaaegm
- valory/termination_abci:0.1.0:bafybeieqpy3nu7qoy6ztfxetgiuevmgcpylufou3ngh5nw2vsgsvghid54
- valory/transaction_settlement_abci:0.1.0:bafybeihuzoxkhnpep4zcekdq463hopohj3i7rkxvbc2ywmmcyppi3knbxy
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.34.0
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/impact_evaluator_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: valory/impact_evaluator_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: /logs
  params:
    args:
      broadcast_to_server: false
      history_end: null
      ceramic_api_base: ${str:https://ceramic-clay.3boxlabs.com/}
      ceramic_api_commit_endpoint: ${str:api/v0/commits}
      ceramic_api_read_endpoint: ${str:api/v0/commits/{stream_id}}
      ceramic_did_seed: ${str:0101010101010101010101010101010101010101010101010101010101010101}
      ceramic_did_str: ${str:z6Mkon3Necd6NkkyfoGoHxid2znGc59LU3K7mubaRcFbLfLX}
      default_read_stream_id: ${str:default_read_stream_id}
      default_write_stream_id: ${str:default_write_stream_id}
      default_read_target_property: ${str:default_read_target_property}
      default_write_target_property: ${str:default_write_target_property}
      manual_points_stream_id: ${str:manual_points_stream_id}
      manual_points_target_property: ${str:score_data}
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      dynamic_contribution_contract_address: ${str:0x5FbDB2315678afecb367f032d93F642f64180aa3}
      earliest_block_to_monitor: ${int:8053690}
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0x0000000000000000000000000000000000000000}
      termination_sleep: ${int:900}
      init_fallback_gas: 0
      keeper_allowed_retries: 3
      reset_pause_duration: ${int:300}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: 2
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      service_id: impact_evaluator
      service_registry_address: ${str:null}
      setup:
        all_participants: ${list:[]}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      token_uri_base: ${str:https://pfp.staging.autonolas.tech/}
      whitelist_api_key: null
      whitelist_endpoint: http://localhost
      points_to_image_hashes: ${str:null}
      twitter_api_base: ${str:https://api.twitter.com/}
      twitter_api_bearer_token: ${str:<default_bearer_token>}
      twitter_mentions_endpoint: ${str:2/users/1450081635559428107/mentions?}
      twitter_mentions_args: ${str:tweet.fields=author_id&user.fields=name&expansions=author_id&max_results=100&since_id={since_id}}
      twitter_max_pages: 10
      twitter_mention_points: ${int:200}
      twitter_search_endpoint: ${str:2/tweets/search/recent?}
      twitter_search_args: ${str:query=%23autonolas&tweet.fields=author_id,created_at&max_results=100}
      tx_timeout: 10.0
      use_termination: ${bool:false}
      validate_timeout: 1205
      finalize_timeout: 60.0
      history_check_timeout: 1205
---
public_id: fetchai/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/impact_evaluator_abci:0.1.0
