agent_name: impact_evaluator
author: valory
version: 0.1.0
license: Apache-2.0
description: The impact evaluator agent.
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeialhcja5fhf2ahyx5no2aajvnfhh4tj7ihhx65qpoohc4n5wfr76q
  tests/__init__.py: bafybeibknjewfed3d5ypi46ipuzfxdcps5ief2hfd3a2tfvm4gjtzzblme
  tests/helpers/__init__.py: bafybeif7verbag26h6i35gr5rlatxl7veq4drup5ykwdvhgtussf2jreei
  tests/helpers/constants.py: bafybeibbokz7gzdlubnjwxrmh4tqckc7j75hfy3ae6l5a63mrbd4hp6l7u
  tests/helpers/data/json_server/data.json: bafybeid3uvl3vnmudpanc64wgwdvxwlyajnuolivrqpdypa5ortdb66a6a
  tests/helpers/docker.py: bafybeihlg5thdrcaiuzyte5s7x25mikqfyxdjwuqvhmeddluyjdkzhuhqi
  tests/helpers/fixtures.py: bafybeidfsamzdrqqkdra4ektollyfkhiyb2iqymy6djavgewon2cb23vwu
  tests/test_impact_evaluator.py: bafybeigu6nx4j4ll7neegopt5h55ijvbaj7depnyjpo5e2z6bsnfci6hs4
fingerprint_ignore_patterns: []
connections:
- valory/http_server:0.22.0:bafybeic3jpkum7g6qo6x6vdrmvvhj7vqw7ec2op72uc3yfhmnlp5hn3joy
- valory/abci:0.1.0:bafybeidn5gc6y3a6tkhgv753kkiub3mfas3tkemm4fs7i4kc4klkjlxpui
- valory/http_client:0.23.0:bafybeid5ffvg76ejjoese7brj5ji3lx66cu7p2ixfwflpo6rgofkypfd7y
- valory/ledger:0.19.0:bafybeibdsjmy4w2eyilbqc7yzutopl65qpeyspxwz7mjvirr52twhjlf5y
- valory/p2p_libp2p_client:0.1.0:bafybeic6ayusdwy4dks75njwk32ac7ur7salgllwf4fdc34ue5z2k5iz4q
- valory/openai:0.1.0:bafybeicm2uvsixb53fh4nl4ib4zzvd36yvvw4hqxslv73eskvecirpm2pu
- valory/twitter:0.1.0:bafybeicwav25v43cx7mrhyjdxrzuyujjqvfvvgtumfajbqfwx4te4pa3k4
contracts:
- valory/dynamic_contribution:0.1.0:bafybeie76wsemqek64b2sm4bidkewqzylokeid7efbuyj26kd44iezi4ia
- valory/gnosis_safe:0.1.0:bafybeibgpgpi7w6xtxg3zr7tye3f6g6tu7fnvy7yxlgunbjqin3ou7e5pi
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeidfvyc6bw4uigv3jfcxr23vysctki6x5rh5htp2azhncib27ydxdm
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- valory/service_registry:0.1.0:bafybeigaginvk2i6rycppfomk6tldkvunik6atuxtjpuuw6ndckymcojne
- valory/veolas_delegation:0.1.0:bafybeifcgvimvu66w273ednm7w765bxjto34aqapfoqkagctgyvfycgeei
- valory/mech_marketplace:0.1.0:bafybeibxvb5txtnho4rc4hz3clghropfdfschthqxtcdai7hx2zycgdjga
- valory/mech_marketplace_legacy:0.1.0:bafybeiafwem7v7po7xb7rag4zfdqe2uoaqki3xybviciypxr5w6zkoxgse
- valory/staking:0.1.0:bafybeihqox2s4v6m3eirukxs4ducepr4zvvwazinb2cxmw7ycpig4ppoeu
- valory/agent_registry:0.1.0:bafybeiepkbcx5jrcvoc5nfarw6gt4so4izqxuiliu7gukdvmjiodynecvy
protocols:
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
- valory/abci:0.1.0:bafybeiatodhboj6a3p35x4f4b342lzk6ckxpud23awnqbxwjeon3k5y36u
- valory/acn:1.1.0:bafybeic6h55ov5lrzbah6fate54c4u6spopcexxspw3abotbmffabfddeu
- valory/contract_api:1.0.0:bafybeid247uig2ekykdumh7ewhp2cdq7rchaeqjj6e7urx35zfpdl5zrn4
- valory/http:1.0.0:bafybeih4azmfwtamdbkhztkm4xitep3gx6tfdnoz6tvllmaqnhu3klejfa
- valory/ipfs:0.1.0:bafybeifi2nri7sprmkez4rqzwb4lnu6peoy3bax5k6asf6k5ms7kmjpmkq
- valory/ledger_api:1.0.0:bafybeihmqzcbj6t7vxz2aehd5726ofnzsfjs5cwlf42ro4tn6i34cbfrc4
- valory/llm:1.0.0:bafybeihj2orqapokafg7co3wlogwgf6cckaaj2bz3nuv4rm3opkoyhrlp4
- valory/tendermint:0.1.0:bafybeigydrbfrlmr4f7shbtqx44kvmbg22im27mxdap2e3m5tkti6t445y
- valory/twitter:0.1.0:bafybeig7dugazhljpb4qtu4zfnoimttvivopiq574rogjz3qggf5eysnk4
skills:
- valory/abstract_abci:0.1.0:bafybeibfsmbjasqnb3lgmwj7dlxvlfbngdyqc7a4n5q2g7phvmv4ktehq4
- valory/abstract_round_abci:0.1.0:bafybeiey45kkbniukmtpdjduwazpyygaiayeo7mh3tu6wfbau2bxvuljmy
- valory/impact_evaluator_abci:0.1.0:bafybeif5wh2ybh7gegkxe4bs6qe4wimb6mpnf3gqmy3cy7556fxzbwbjwq
- valory/twitter_scoring_abci:0.1.0:bafybeibt6gaonyi6erlihv54k5njzj4cyetchlfrfoi2wi45okce3oxvvy
- valory/agent_db_abci:0.1.0:bafybeig5vmynr4xsyjln6kydse72jbm56mkryv34aflj47gaai5t3g4hgm
- valory/contribute_db_abci:0.1.0:bafybeieofmuca5rqxpidqsl3fdvpc4kt6hmwrglwl6la36w6e4e2h4y2w4
- valory/dynamic_nft_abci:0.1.0:bafybeidan76pecwrbmv4rtteh3zmmuxkvptqflncizzcvsrbfpk7z47mi4
- valory/registration_abci:0.1.0:bafybeidqadl26x5prbjgnkqrvjnbqxpo75jttm7vlvpgkoqghs5677rw5i
- valory/reset_pause_abci:0.1.0:bafybeiachgo6reit2q4jw75mefw2acj4ldedeqmn3rewjm4dbzts2l7oxe
- valory/termination_abci:0.1.0:bafybeibtbboau3q5fxfviwm7lbeix4z55uptfqqiyiu6siivxwkp3o5pju
- valory/transaction_settlement_abci:0.1.0:bafybeic2ywzpwkyeqbzsvkbvurhsptemam4xtceihax2tmxmlxtgd3xpya
- valory/twitter_write_abci:0.1.0:bafybeiamg6pt2rejxftvgmjxvmicy3b3rxxaqpk2h3k7h3pgh4sfitttv4
- valory/decision_making_abci:0.1.0:bafybeiedj5rps46y6tkqv6znqf55pt6ja73gvzxoyjyp3gwnppa7ex3ziy
- valory/olas_week_abci:0.1.0:bafybeiasd2lf4wthmamkozukyprxtpyk4fb4nwyfkcqc7uergq6lwmi3n4
- valory/mech_interact_abci:0.1.0:bafybeidi2nfkt5r7cckdd4equdfm5uwiuisrz2splo7om3hkriy5ohx22e
- valory/staking_abci:0.1.0:bafybeiaey3na6tcmsztul3ek3iu4v66mzem7k6cg7h3w76rql2fl5xmjsa
- valory/llm_abci:0.1.0:bafybeigdt4i64l5ftfbxrk656myrxer2vgti2mkllfhfybzjmosqgj5the
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.65.0
  typing_extensions:
    version: ==4.13.2
default_connection: null
---
public_id: valory/openai:0.1.0
type: connection
config:
  engine: ${str:gpt-4}
  max_tokens: ${int:500}
  openai_api_key: ${str:null}
  temperature: ${float:0.7}
  use_openai_staging_api: ${bool:false}
  openai_staging_api: ${str:http://host.docker.internal:5000/openai}
---
public_id: valory/twitter:0.1.0
type: connection
config:
  access_secret: ${str:<access_secret>}
  access_token: ${str:<access_token>}
  auth_token: ${str:<auth_token>}
  consumer_key: ${str:<consumer_key>}
  consumer_secret: ${str:<consumer_secret>}
  use_twitter_staging_api: ${bool:false}
  twitter_staging_api: ${str:http://host.docker.internal:5000/twitter/create_tweet}
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/impact_evaluator_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
      gas_price_strategies: &id001
        gas_station:
          gas_price_api_key: null
          gas_price_strategy: fast
        eip1559:
          max_gas_fast: 1500
          fee_history_blocks: 10
          fee_history_percentile: 5
          default_priority_fee: ${int:null}
          fallback_estimate:
            maxFeePerGas: ${int:20000000000}
            maxPriorityFeePerGas: ${int:3000000000}
          priority_fee_increase_boundary: ${int:200}
    gnosis:
      address: ${str:http://localhost:8545}
      chain_id: ${int:100}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
      gas_price_strategies: *id001
    base:
      address: ${str:http://localhost:8545}
      chain_id: ${int:8453}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
      gas_price_strategies: *id001
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: valory/impact_evaluator_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/logs}
  params:
    args:
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      dynamic_contribution_contract_address: ${str:0x5FbDB2315678afecb367f032d93F642f64180aa3}
      earliest_block_to_monitor: ${int:8053690}
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      termination_sleep: ${int:900}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: 3
      reset_pause_duration: ${int:300}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: ${int:2}
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      tweet_evaluation_round_timeout: ${float:600.0}
      service_id: impact_evaluator
      service_registry_address: ${str:null}
      setup:
        all_participants: ${list:["0x10E867Ac2Fb0Aa156ca81eF440a5cdf373bE1AaC"]}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      token_uri_base: ${str:https://pfp.staging.autonolas.tech/}
      whitelist_api_key: null
      whitelist_endpoint: http://localhost
      points_to_image_hashes: ${str:{}}
      twitter_api_base: ${str:https://api.twitter.com/}
      twitter_api_bearer_token: ${str:<default_bearer_token>}
      twitter_mentions_endpoint: ${str:2/users/1450081635559428107/mentions?}
      twitter_mentions_args: ${str:tweet.fields=author_id,created_at,public_metrics&user.fields=name&expansions=author_id&max_results={max_results}&since_id={since_id}}
      twitter_max_pages: ${int:1}
      max_tweet_pulls_allowed: ${int:120}
      twitter_search_endpoint: ${str:2/tweets/search/recent?}
      twitter_search_args: ${str:query={search_query}&tweet.fields=author_id,created_at,conversation_id,public_metrics&user.fields=name&expansions=author_id&max_results={max_results}&since_id={since_id}}
      twitter_tweets_endpoint: ${str:2/users/1450081635559428107/tweets?}
      twitter_tweets_args: ${str:tweet.fields=author_id,created_at,conversation_id,public_metrics&user.fields=name&expansions=author_id&max_results=50&start_time={start_time}}
      openai_call_window_size: ${float:3600.0}
      openai_calls_allowed_in_window: ${int:100}
      tx_timeout: 10.0
      use_termination: ${bool:false}
      validate_timeout: 1205
      finalize_timeout: 60.0
      history_check_timeout: 1205
      centaur_id_to_secrets: ${str:{}}
      max_points_per_period: ${int:1500}
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      multisend_batch_size: ${int:50}
      mech_contract_address: ${str:0x77af31De935740567Cf4fF1986D04B2c964A786a}
      mech_request_price: ${int:null}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      default_chain_id: ${str:ethereum}
      transaction_service_url: ${str:https://safe-transaction-mainnet.safe.global/api/v1/messages/{message_hash}/}
      veolas_delegation_address: ${str:0x2f1ea3bc39f1a052460cac722e64c1f89c3c1e68}
      tweet_consensus_veolas: ${int:2000000}
      termination_from_block: ${int:0}
      mech_chain_id: ${str:gnosis}
      mech_interaction_sleep_time: ${int:10}
      use_mech_marketplace: ${bool:false}
      mech_marketplace_config: ${dict:{"mech_marketplace_address":"0x0000000000000000000000000000000000000000","priority_mech_address":"0x0000000000000000000000000000000000000000","priority_mech_staking_instance_address":"0x0000000000000000000000000000000000000000","priority_mech_service_id":0,"requester_staking_instance_address":"0x0000000000000000000000000000000000000000","response_timeout":300}}
      checkpoint_threshold_minutes: ${int:600}
      staking_activity_threshold: ${int:5}
      staking_contract_addresses: ${list:["0xe2E68dDafbdC0Ae48E39cDd1E778298e9d865cF4","0x6Ce93E724606c365Fc882D4D6dfb4A0a35fE2387","0x28877FFc6583170a4C9eD0121fc3195d06fd3A26"]}
      contributors_contract_address: ${str:0x343F2B005cF6D70bA610CD9F1F1927049414B582}
      epoch_end_threshold_minutes: ${int:60}
      safe_contract_address_base: ${str:0x3316b59A6c4C3ee2920EecE0B02A6d40AAa6b9c9}
      safe_contract_address_gnosis: ${str:0x6B47A6a481dD717526Feaad358fF873f7760B074}
      agent_registry_address: ${str:0x0000000000000000000000000000000000000000}
      use_acn_for_delivers: ${bool:false}
      staking_rewards_required_points: ${int:200}
      disable_wio_posting: ${bool:false}
      contribute_db_pkey: ${str:null}
  randomness_api:
    args:
      api_id: cloudflare
      headers: {}
      method: GET
      parameters: {}
      response_key: null
      response_type: dict
      retries: 5
      url: ${str:https://drand.cloudflare.com/public/latest}
  agent_db_client:
    args:
      base_url: ${str:https://afmdb.autonolas.tech}
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/impact_evaluator_abci:0.1.0
  port: ${int:8000}
