agent_name: impact_evaluator
author: valory
version: 0.1.0
license: Apache-2.0
description: The impact evaluator agent.
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeialhcja5fhf2ahyx5no2aajvnfhh4tj7ihhx65qpoohc4n5wfr76q
  tests/__init__.py: bafybeicmv3jjcqcdnmubfmrgdgeyic3nkm77z4mutsyuo34hpddwupofre
  tests/helpers/__init__.py: bafybeiauwuw4a4wxqacqqkkk52ktps2qedadhypvh3ex7uqs7qaqrpygmy
  tests/helpers/constants.py: bafybeibbokz7gzdlubnjwxrmh4tqckc7j75hfy3ae6l5a63mrbd4hp6l7u
  tests/helpers/data/json_server/data.json: bafybeicn4kcveaawctmhxs2wbxhztteqrs5ak3m7vgyceot5shahvvvoxu
  tests/helpers/docker.py: bafybeihlg5thdrcaiuzyte5s7x25mikqfyxdjwuqvhmeddluyjdkzhuhqi
  tests/helpers/fixtures.py: bafybeid7spk5nuu5chsy5q5qjgw7gui5ysxm77lxru62imyx4ok6fjqreq
  tests/test_impact_evaluator.py: bafybeif7rdginbmc2ssx4sq7ijkg3nvgipbazccpktbzw6kwk2ifpfry6m
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.22.0:bafybeihaax5od5zo5jk2l62hv4jwuwtxloh5mijozudpsjombqc4ncmi6i
- valory/abci:0.1.0:bafybeihhidrulgjlrlvmk2c2ax7qmb47ywzjnjqv5gwp7fzzbcgplgaz5a
- valory/http_client:0.23.0:bafybeidykl4elwbcjkqn32wt5h4h7tlpeqovrcq3c5bcplt6nhpznhgczi
- valory/ledger:0.19.0:bafybeiavzloea5rtoxfdqjuexkqzpgbq73n4sl6af2vwa4bv2wd22qigyi
- valory/p2p_libp2p_client:0.1.0:bafybeidwcobzb7ut3efegoedad7jfckvt2n6prcmd4g7xnkm6hp6aafrva
contracts:
- valory/dynamic_contribution:0.1.0:bafybeiap7dvbkfbh2t5f5sm3k4zlh6rhf4sle4v5d2xakcl2haoeh2qjja
protocols:
- open_aea/signing:1.0.0:bafybeibqlfmikg5hk4phzak6gqzhpkt6akckx7xppbp53mvwt6r73h7tk4
- valory/contract_api:1.0.0:bafybeidv6wxpjyb2sdyibnmmum45et4zcla6tl63bnol6ztyoqvpl4spmy
- valory/http:1.0.0:bafybeifyoio7nlh5zzyn5yz7krkou56l22to3cwg7gw5v5o3vxwklibhty
skills:
- valory/abstract_abci:0.1.0:bafybeiheudaobfaj5lcrqvgwmdysq3za5yjrjtpdiuwhmw5c7lmbgglxti
- valory/abstract_round_abci:0.1.0:bafybeiami2y2uwvtmjf76hl3jvfahujdir5docjby6erdyjl66ekoblesi
- valory/impact_evaluator_abci:0.1.0:bafybeibzwmmzzom6i473sen5x7rhqsqnuunuppnwcudg44pprkbee442oe
- valory/score_read_abci:0.1.0:bafybeiagf7swl56mlgn546rcu6eseaygrerei7qxtmv6kw5nsdqg7judya
- valory/score_write_abci:0.1.0:bafybeielbky5pt5ehxopm2mslkcqoqoldmzclffge2u2w7au6hybd2khaa
- valory/dynamic_nft_abci:0.1.0:bafybeieubi5ewqoraerouuvlm5wuzrec4hhqqj3zahxfgv5vcwuc5viwiq
- valory/registration_abci:0.1.0:bafybeieaggf6mc43tses5k7fg3pyxca43wsmfvnnzszzucohp5ebg3umwq
- valory/reset_pause_abci:0.1.0:bafybeic6ayed23np6ngkawsf2you6nnfuvbq4smcepdvvcrw5wxn5jaevy
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.29.0
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/impact_evaluator_abci:0.1.0
  host: ${ABCI_HOST:str:localhost}
  port: ${ABCI_PORT:int:26658}
  use_tendermint: ${ABCI_USE_TENDERMINT:bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_ADDRESS:str:http://localhost:8545}
      chain_id: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_CHAIN_ID:int:31337}
      poa_chain: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
is_abstract: true
---
public_id: valory/impact_evaluator_abci:0.1.0
type: skill
models:
  params:
    args:
      ceramic_api_base: ${str:https://ceramic-clay.3boxlabs.com/}
      ceramic_api_commit_endpoint: ${str:api/v0/commits}
      ceramic_api_read_endpoint: ${str:api/v0/commits/{stream_id}}
      ceramic_did_seed: ${str:0101010101010101010101010101010101010101010101010101010101010101}
      ceramic_did_str: ${str:z6Mkon3Necd6NkkyfoGoHxid2znGc59LU3K7mubaRcFbLfLX}
      scores_stream_id: ${str:user_to_points_stream_id}
      wallets_stream_id: ${str:wallet_to_users_stream_id}
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      earliest_block_to_monitor: ${int:8053690}
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      keeper_timeout: 30.0
      max_healthcheck: 120
      observation_interval: ${int:300}
      on_chain_service_id: null
      reset_tendermint_after: 2
      retry_attempts: 400
      retry_timeout: 3
      round_timeout_seconds: 30.0
      service_id: impact_evaluator
      service_registry_address: null
      setup:
        all_participants: ${list:[]}
        safe_contract_address: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold:
        - null
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      dynamic_contribution_contract_address: ${str:0x5FbDB2315678afecb367f032d93F642f64180aa3}
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      token_uri_base: ${str:https://pfp.staging.autonolas.tech/}
      whitelist_api_key: null
      whitelist_endpoint: http://localhost
      points_to_image_hashes: ${str:null}
      twitter_api_base: ${str:https://api.twitter.com/}
      twitter_api_bearer_token: ${str:<default_bearer_token>}
      twitter_api_endpoint: ${str:2/users/1450081635559428107/mentions?}
      twitter_api_args: ${str:tweet.fields=author_id&user.fields=name&max_results=100&since_id={since_id}}
      twitter_mention_points: ${int:200}
      twitter_max_pages: 10
---
public_id: fetchai/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/impact_evaluator_abci:0.1.0
