# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twitter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rtwitter.proto\x12\x19\x61\x65\x61.valory.twitter.v0_1_0"\x99\x02\n\x0eTwitterMessage\x12Q\n\x07request\x18\x05 \x01(\x0b\x32>.aea.valory.twitter.v0_1_0.TwitterMessage.Request_PerformativeH\x00\x12S\n\x08response\x18\x06 \x01(\x0b\x32?.aea.valory.twitter.v0_1_0.TwitterMessage.Response_PerformativeH\x00\x1a$\n\x14Request_Performative\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x1a)\n\x15Response_Performative\x12\x10\n\x08tweet_id\x18\x01 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "twitter_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_TWITTERMESSAGE"]._serialized_start = 45
    _globals["_TWITTERMESSAGE"]._serialized_end = 326
    _globals["_TWITTERMESSAGE_REQUEST_PERFORMATIVE"]._serialized_start = 231
    _globals["_TWITTERMESSAGE_REQUEST_PERFORMATIVE"]._serialized_end = 267
    _globals["_TWITTERMESSAGE_RESPONSE_PERFORMATIVE"]._serialized_start = 269
    _globals["_TWITTERMESSAGE_RESPONSE_PERFORMATIVE"]._serialized_end = 310
# @@protoc_insertion_point(module_scope)
